import JSZip from 'jszip';
import { ProjectSettings } from '@/types/keyboard';
import { getRmkChip, RmkExportFormat, usesRmkAdafruitBootloader } from './rmk-hardware';
import rpCargo from './rmk-templates/rp2040.Cargo.toml.txt?raw';
import nrfCargo from './rmk-templates/nrf52840_ble.Cargo.toml.txt?raw';
import license from './rmk-templates/LICENSE-MIT.txt?raw';

/** Build support shared by the config-macro and explicit Rust API entry points. */
export const addRmkProjectFiles = (zip: JSZip, settings: ProjectSettings, name: string, format: RmkExportFormat) => {
  const chip = getRmkChip(settings);
  const fullProject = ['rp2040', 'nrf52840', 'nrf52833'].includes(chip);
  const nrf = chip === 'nrf52840' || chip === 'nrf52833';
  const nrf33 = chip === 'nrf52833';
  const adafruit = usesRmkAdafruitBootloader(settings);
  const split = settings.features.split;
  zip.file('LICENSE-RMK-MIT.txt', license);
  if (!fullProject) {
    zip.file('Cargo.toml', `[package]\nname = "${name}"\nversion = "0.1.0"\nedition = "2024"\n\n[dependencies]\nrmk = "=0.9.0"\n`);
  } else {
    const cargoTemplate = nrf ? (nrf33 ? nrfCargo.replaceAll('nrf52840', 'nrf52833') : nrfCargo) : rpCargo;
    let cargo = cargoTemplate
      .replace(/\[package\][\s\S]*?\[dependencies\]/, `[package]\nname = "${name}"\nversion = "0.1.0"\nedition = "2024"\n\n[dependencies]`)
      .replace('path = "../../../rmk"', 'version = "=0.9.0"')
      .replace(', "adafruit_bl"', '')
      .replace(/\[\[bin\]\][\s\S]*?(?=\[profile.dev\])/, (split ? ['central', 'peripheral'] : ['main']).map(bin => `[[bin]]\nname = "${split ? bin : name}"\npath = "src/${bin}.rs"\ntest = false\nbench = false\n\n`).join(''));
    if (split) cargo = cargo.replace('"watchdog",', '"watchdog", "split",');
    if (adafruit) cargo = cargo.replace('"watchdog",', '"watchdog", "adafruit_bl",');
    if (!nrf) cargo = cargo.replace('[dependencies]', '[dependencies]\nstatic_cell = "2"');
    zip.file('Cargo.toml', cargo);
    zip.file('.cargo/config.toml', `[build]\ntarget = "${nrf ? 'thumbv7em-none-eabihf' : 'thumbv6m-none-eabi'}"\n\n[env]\nDEFMT_LOG = "info"\nKEYBOARD_TOML_PATH = { value = "keyboard.toml", relative = true }\n`);
    zip.file('rust-toolchain.toml', `[toolchain]\nchannel = "stable"\ntargets = ["${nrf ? 'thumbv7em-none-eabihf' : 'thumbv6m-none-eabi'}"]\n`);
    // Reserve storage and keep bootloader-specific vector origins consistent with Cargo features.
    zip.file('memory.x', nrf ? `MEMORY {
  FLASH : ORIGIN = ${adafruit ? '0x00001000' : '0x00000000'}, LENGTH = ${adafruit ? '0xDF000' : nrf33 ? '0x78000' : '0xE0000'}
  RAM : ORIGIN = ${adafruit ? '0x20000008' : '0x20000000'}, LENGTH = ${adafruit ? '0x3FFF8' : nrf33 ? '0x20000' : '0x40000'}
}
` : `MEMORY {
  BOOT2 : ORIGIN = 0x10000000, LENGTH = 0x100
  FLASH : ORIGIN = 0x10000100, LENGTH = 2048K - 0x100
  RAM : ORIGIN = 0x20000000, LENGTH = 256K
}
EXTERN(BOOT2_FIRMWARE)
SECTIONS { .boot2 ORIGIN(BOOT2) : { KEEP(*(.boot2)); } > BOOT2 } INSERT BEFORE .text;
`);
    const uid = (settings.vialUid || 'B9BC09B29D374CEA').replace(/^0x/i, '');
    if (!/^[0-9a-f]{16}$/i.test(uid)) throw new Error('Vial UID must contain exactly 16 hexadecimal digits.');
    zip.file('build.rs', `use std::{env, fs, io::Read, path::PathBuf};
fn main() {
    let out = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    fs::write(out.join("memory.x"), include_bytes!("memory.x")).unwrap();
    println!("cargo:rustc-link-search={}", out.display());
    println!("cargo:rustc-link-arg=--nmagic");
    println!("cargo:rustc-link-arg=-Tlink.x");
    println!("cargo:rustc-link-arg=-Tdefmt.x");
    println!("cargo:rerun-if-changed=memory.x");
    println!("cargo:rerun-if-changed=vial.json");
    println!("cargo:rerun-if-changed=keyboard.toml");
    let source = fs::read_to_string("vial.json").unwrap();
    let compact = json::stringify(json::parse(&source).unwrap());
    let mut compressed = Vec::new();
    xz2::read::XzEncoder::new(compact.as_bytes(), 6).read_to_end(&mut compressed).unwrap();
    fs::write(out.join("config_generated.rs"), format!("pub const VIAL_KEYBOARD_DEF: &[u8] = &{:?};\\npub const VIAL_KEYBOARD_ID: &[u8] = &[${uid.match(/../g)!.map(byte => `0x${byte}`).join(', ')}];\\n", compressed)).unwrap();
}
`);
    zip.file('src/vial.rs', 'include!(concat!(env!("OUT_DIR"), "/config_generated.rs"));\n');
    if (format === 'toml') {
      for (const bin of split ? ['central', 'peripheral'] : ['main']) {
        const macro = bin === 'main' ? 'rmk_keyboard' : `rmk_${bin}`;
        zip.file(`src/${bin}.rs`, `#![no_std]\n#![no_main]\n\n#[rmk::macros::${macro}${bin === 'peripheral' ? '(id = 0)' : ''}]\nmod keyboard {}\n`);
      }
    }
  }
  zip.file('README.md', `# RMK 0.9.0 — ${settings.name}

Generated by Smiðr. Export format: ${format === 'rust' ? 'Rust API' : 'TOML'}.

${format === 'rust' ? 'The entry points explicitly initialize the matrix, keymap, transports, PMW3610 devices and pointing processors using RMK 0.9 APIs. Edit src/keymap.rs and src/main.rs (or src/central.rs and src/peripheral.rs). keyboard.toml records the equivalent configuration and supplies RMK compile-time capacities; its keymap and GPIO definitions do not override the Rust source.' : 'Edit keyboard.toml. The Rust entry points use RMK configuration macros.'}

${fullProject ? `## Build

Install Rust stable and the native build tools for your OS (including a C compiler for xz2${nrf ? ', Arm GNU Toolchain and libclang for the Nordic dependencies' : ''}), then run:

\`\`\`sh
${split ? 'cargo build --release --bin central\ncargo build --release --bin peripheral' : 'cargo build --release'}
\`\`\`

Target: ${chip}. ${nrf ? `Vector origin is ${adafruit ? '0x1000 (Adafruit UF2 bootloader)' : '0x0 (direct SWD flashing)'}. Storage uses ${nrf33 ? '0x78000–0x7FFFF' : '0xE0000–0xE7FFF'}. Confirm memory.x against your bootloader before flashing. BLE peers must be re-paired when migrating from RMK 0.8.` : 'The linker assumes 2 MiB of external flash. Adjust memory.x and the Rust Flash size if your board differs.'}` : '## Integration required\n\nThis MCU receives TOML configuration only. Add it to the matching RMK 0.9 board example and supply its HAL dependencies, entry points and linker configuration before building.'}

## Pointing devices

PMW3610 uses bit-banged single-wire SPI. SCLK, SDIO and CS are required; MOTION is optional (polling when omitted). CPI, axis swap and inversions are preserved. Split peripherals forward sensor IDs; their pointing processors run on the central.

## Current limits

Project macro bodies, combos, encoders and lighting configuration are not generated. Assignments to these features may need follow-up code. Bidirectional matrices with shared row/column pins are not generated. Raw RMK expressions in Rust mode must be supported by the action converter.

The supporting templates derive from https://github.com/rmk-rs/rmk/tree/rmk-v0.9.0/examples (MIT; see LICENSE-RMK-MIT.txt).
`);
};
